/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mati' at '22/02/16 12:09' with Gradle 2.6
 *
 * @author mati, @date 22/02/16 12:09
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
